name: Sync Spark Jobs to GCS

on:
  push:
    branches:
      - main
    paths:
      - 'spark_jobs/**'  # Only triggers if files in this folder change

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Upload Scripts to GCS
        run: |
          # rsync makes sure we only upload changed files
          gsutil -m rsync -r ./spark_jobs gs://${{ secrets.GCS_BUCKET_NAME }}/scripts